<?php

const PENDING_STATUS = 0;
const ACTIVE_STATUS = 1;
const INACTIVE_STATUS = 2;
const DELETE_STATUS = 3;

const ADMIN_ROLE = 1;
const USER_ROLE = 2;

const DEPOSIT_TYPE = 1;
const WITHDRAWAL_TYPE = 2;
const REFER_BONUS_TYPE = 3;

const WITHDRAWAL_APPROVED_STATUS = 1;
const WITHDRAWAL_REJECT_STATUS = 2;

const CASH_IN = 1;
const CASH_OUT = 2;
